---
- name: install nginx packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=86400
  with_items:
    - nginx
  tags:
    - nginx

- name: create document root directory if needed
  file: path={{ nginx.document_root }} state=directory mode=0755
  tags:
    - nginx

#- name: Starting nginx service
#  service: name=nginx state=started
#  tags:
#    - nginx

- name: copy nginx default conf
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx
  tags:
    - nginx

- name: copy nginx default site
  template: src=default.{{ nginx.php_engine }}.j2 dest={{ nginx.vhost_path }}
  notify: reload nginx
  tags:
    - nginx

- name: create document root directory if needed
  file: path={{ nginx.document_root }} state=directory mode=0755
  tags:
    - nginx

- name: copy phpinfo
  template: src=index.php.j2 dest={{ nginx.document_root }}index.php
  notify: restart nginx
  tags:
    - nginx
